### ISSUE TITLE
feature request: user-submitted DOYs for microclimate model?

### ISSUE THREAD

**Issue by dklinges9** [mrke/NicheMapR#10]
Hi Mike,

For one of my current uses, I was hoping to run `micro_global()` for just a subset of winter days (let's say 12 days in a row in winter). But due to computational restraints (the project entails a large spatiotemporal scale) I can't afford to run the model for `timeinterval = 365` and then subset to just my few days of interest. So I wanted to see if it's possible to have user-submitted choice of DOYs handed to `micro_global()` or the other microclimate model wrappers.  

My tampering with things in `micro_global()` by adding an argument for user's choice of`doys` to replace `doys12` ended up not changing anything, even if `doys` was also 12 days (`micro_global()` returned the same output as it did for middle-of-each-month 12 days)....so I'm guessing there's more to this than my simple approach ([see here](https://github.com/dklinges9/NicheMapR_dev/commit/ef8f6e392ff5b3a60db3e02ac0f316c2e40f8268) for my tampering). 

Would it be a heavy lift to allow users to choose the specific days of the year to run the microclimate model? From my understanding of how daily initial conditions are set, this might be straightforward to do if the DOYs are right next to each other, but less so if it's a random subset of the year. I'd imagine there may be other users who are also interested in just a particular temporal window but have similar computational restraints that prevent running for 365 days.    

Apologies if I've missed that this functionality is already available somewhere. And as always, thanks for your hard and consistent work on the package.  

Cheers, Dave

**Comment by mrke** [comment]
Hi Dave,

I'd prefer to keep micro_global as is and that you modify it for your specific purpose. 

To achieve this you could add your input vector 'doys' of the days of year you want to do, and then add the code below at line 962 of the original version (i.e. after the splining to 365 days has been done and before the dummy hourly vectors are specified). 

Note that you have to run with timeinterval = 365 and nyears = 1 for this to work and they need to be consecutive days. The model will run the first day you specify three times to initialise and then the next days will start with the conditions of the previous day, but this won't be enough to initialise the soil moisture and snow, so you should turn off the snow and soil moisture models.

So, after adding the doys input and the code below, running it would look e.g. like:

doys <- seq(180, 190)
micro_global(doys = doys, timeinterval = 365, runmoist = 0, snowmodel = 0)

All the best,
Mike

code to insert at line 962 (i.e. before the comment "# hourly option set to 0, so make empty vectors"):
doy <- doys
ndays <- length(doy)
ida <- ndays
SLES <- SLES[doy]
Nodes <- Nodes[, doy]
MAXSHADES <- MAXSHADES[doy]
MINSHADES <- MINSHADES[doy]
TMAXX <- TMAXX[doy]
TMINN <- TMINN[doy]
RHMAXX <- RHMAXX[doy]
RHMINN <- RHMINN[doy]
CCMAXX <- CCMAXX[doy]
CCMINN <- CCMINN[doy]
WNMAXX <- WNMAXX[doy]
WNMINN <- WNMINN[doy]
REFLS <- REFLS[doy]
PCTWET <- PCTWET[doy]
moists <- moists[, doy]
RAINFALL <- RAINFALL[doy]
tannulrun <- tannulrun[doy]

**Comment by dklinges9** [comment]
Thanks Mike, it looks like this saves a little bit of time as compared to simply running micro_global(timeinterval = 365) and then subsetting the output, so appreciate it!
