### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by sfmatter** [mrke/NicheMapR#13]
Is there a version  for R 4.0?

I get the error

Error: package or namespace load failed for ‘NicheMapR’:
 package ‘NicheMapR’ was installed before R 4.0.0: please re-install it

**Comment by fipoucat** [comment]
I have the same problem and expect Mike to update the binaries, in my case the mac version.
Hope he'll get time to do it or if someone can post it please.

Thanks

**Comment by mrke** [comment]
I’ll make the new binaries later this month as part of a new release. In the meantime, hopefully you can use devtools::install_github to install the current version on R v4.
All the best,
Mike

From: fipoucat ***@***.***>
Sent: Friday, 2 April 2021 1:47 AM
To: mrke/NicheMapR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] Re: [mrke/NicheMapR] New version? (#13)

UoM notice: External email. Be cautious of links, attachments, or impersonation attempts

________________________________
I have the same problem and expect Mike to update the binaries, in my case the mac version.
Hope he'll get time to do it or if someone can post it please.

Thanks

**Comment by fipoucat** [comment]
Thank you, I'll wait the binaries, I tried many times
devtools::install_github() gives always error message.

Thanks
