### ISSUE TITLE
error in NicheMapR/R/micro_uk.R

### ISSUE THREAD

**Issue by dswethey** [mrke/NicheMapR#14]
micro_uk.R line 658

ov <- jsonlite::jsonlite::fromJSON(paste0('https://rest.soilgrids.org/query?lon=',x[1],'&lat=',x[2],',&attributes=BLDFIE,SLTPPT,SNDPPT,CLYPPT'), flatten = TRUE)

should have only one instance of jsonlite::

this causes installation failure on linux.

**Comment by mrke** [comment]
Thanks - fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: dswethey ***@***.***>
Sent: Sunday, May 9, 2021 2:38:35 AM
To: mrke/NicheMapR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [mrke/NicheMapR] error in NicheMapR/R/micro_uk.R (#14)


External email: Please exercise caution

________________________________
micro_uk.R line 658

ov <- jsonlite::jsonlite::fromJSON(paste0('https://rest.soilgrids.org/query?lon=',x[1],'&lat=',x[2],',&attributes=BLDFIE,SLTPPT,SNDPPT,CLYPPT<https://rest.soilgrids.org/query?lon=',x%5B1%5D,'&lat=',x%5B2%5D,',&attributes=BLDFIE,SLTPPT,SNDPPT,CLYPPT>'), flatten = TRUE)

should have only one instance of jsonlite::

this causes installation failure on linux.

**Comment by dswethey** [comment]
Ubuntu 20.04.2 LTS / R 4.0.4 installation via install_github() now works properly.  Thanks
