### ISSUE TITLE
reminder to change function names

### ISSUE THREAD

**Issue by everydayduffy** [mrke/NicheMapR#15]
Latest version of mcera5 has different function names:

e.g. https://github.com/mrke/NicheMapR/blob/595d04b11d60e562d30d7f3a7d69ce1c0c779c85/R/micro_era5.R#L741

You'll need to change:

point_nc_to_df -> extract_clim
point_nc_to_df_precip -> extract_precip

Cheers,

James

**Comment by manmatej** [comment]
Hello, I just would like to support the update of the package. It this state `micro_era5` function is not working. Only solution which worked for me was to use older `mcera5` release
 
`remotes::install_github("everydayduffy/mcera5@fd8e8ab3cbc090bd996fdcf6fa72f6923e67a602")`
