### ISSUE TITLE
R 4 binary for mac

### ISSUE THREAD

**Issue by fipoucat** [mrke/NicheMapR#17]
Thank you for the new version, nice effort. Could also post a binary for mac (.tgz) compile with R version 4?

Thanks

**Comment by fipoucat** [comment]
Still trying to install on mac with the master.zip file without success. Any hint to support the install using R4?

**Comment by mrke** [comment]
Sorry - will get to this in the next couple of weeks. Still can't install with devtools::install_github?

**Comment by mrke** [comment]
Hi Diego and fipoucat,

I have spent quite a bit of time trying to build the binaries for mac with the machine I have available to me, which is running Big Sur on a M1 chip to no avail. I tried the various options [here](https://github.com/fxcoudert/gfortran-for-macOS/releases) and tried installing gcc via homebrew but though some options allowed compilation to finish, the dll couldn't be found when I tried to run any NicheMapR functions with calls to Fortran. I can only suggest that for the time being you try and use the link I provided in the previous sentence to install gfortran locally on your machine and then try `devtools::install_github('mrke/NicheMapR')`.

All the best,
Mike

**Comment by mrke** [comment]
I spoke too soon - I successfully installed it (under Big Sur, M1 chip) after installing gcc and command line tools via homebrew and then creating a Makevars file with the following:

`FLIBS=-L/usr/local/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0 -L/usr/local/gfortran/lib -lgfortran -lm
CXX1X=/usr/local/gfortran/bin/g++
CXX98=/usr/local/gfortran/bin/g++
CXX11=/usr/local/gfortran/bin/g++
CXX14=/usr/local/gfortran/bin/g++
CXX17=/usr/local/gfortran/bin/g++

LLVM_LOC = /usr/local/opt/llvm
CC=/usr/local/gfortran/bin/gcc
CXX=/usr/local/gfortran/bin/g++
CFLAGS=-I/opt/homebrew/include
CPPFLAGS=-I/opt/homebrew/include
CXXFLAGS=-I/opt/homebrew/include
CXX11FLAGS=-I/opt/homebrew/include
LDFLAGS=-L/opt/homebrew/lib`

One part of my problem was not having installed the right version of R for the Mac I was using (I installed a version that worked but which couldn't compile). I have just added the new binary to the latest pre-release.
