### ISSUE TITLE
rain imputation in micro_global errors where months have no rain days

### ISSUE THREAD

**Issue by goldingn** [mrke/NicheMapR#22]
I'm running some microclimate models for dry places, and some spots have no rainy days in some months in the micro_global() source data. Niamey, Niger is one example. This leads to divide-by-zeros putting NAs in the rainfall data, when used with daily predictions and `rainfrac=0`, and then the fortran bit errors:

``` r
library(NicheMapR)
micro <- micro_global(
  loc = c(2.0840132, 13.5127664),
  timeinterval = 365,
  rainfrac = 0
)
#> If program is crashing, try run.gads = 2.
#> extracting climate data
#> extracting soil moisture data
#> running microclimate model for 365 days by 1 years at site long 2.0840132 lat 13.5127664
#> Note: the output column `SOLR` in metout and shadmet is for unshaded horizontal plane solar radiation
#> Error in microclimate(micro): NA/NaN/Inf in foreign function call (arg 24)
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The offending lines are here (but possibly duplicated in other parts of the package?), and could be patched with some error handling

https://github.com/mrke/NicheMapR/blob/329eb11495b6f89cee8cda4bab4eb56e147c0313/R/micro_global.R#L915-L919

**Comment by mrke** [comment]
OK fixed it by just putting a check for NA after the rainfall vector has been constructed and setting NA to zero.

From: Nick Golding ***@***.***>
Sent: Friday, August 18, 2023 2:44 PM
To: mrke/NicheMapR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mrke/NicheMapR] rain imputation in micro_global errors where months have no rain days (Issue #22)


I'm running some microclimate models for dry places, and some spots have no rainy days in some months in the micro_global() source data. Niamey, Niger is one example. This leads to divide-by-zeros putting NAs in the rainfall data, when used with daily predictions and rainfrac=0, and then the fortran bit errors:

library(NicheMapR)

micro <- micro_global(

  loc = c(2.0840132, 13.5127664),

  timeinterval = 365,

  rainfrac = 0

)

#> If program is crashing, try run.gads = 2.

#> extracting climate data

#> extracting soil moisture data

#> running microclimate model for 365 days by 1 years at site long 2.0840132 lat 13.5127664

#> Note: the output column `SOLR` in metout and shadmet is for unshaded horizontal plane solar radiation

#> Error in microclimate(micro): NA/NaN/Inf in foreign function call (arg 24)

Created on 2023-08-18 with reprex v2.0.2<https://reprex.tidyverse.org>

The offending lines are here (but possibly duplicated in other parts of the package?), and could be patched with some error handling

https://github.com/mrke/NicheMapR/blob/329eb11495b6f89cee8cda4bab4eb56e147c0313/R/micro_global.R#L915-L919

**Comment by goldingn** [comment]
Awesome! So speedy, thanks Mike!

**Comment by goldingn** [comment]
Actually, I'm getting another related error now, where it's infilling Inf for the divide by 0. Previously it was 0 rainfall over 0 rainy days (`0/0` = `NA`), but now I have non-zero rainfall on zero rainy days (`1/0` = `Inf`).
A quick fix would be to change this line: https://github.com/mrke/NicheMapR/blob/f3ed05e5ee6bd20828dab2cbf02a029b8cc39310/R/micro_global.R#L933
to:
`RAINFALL[!is.finite(RAINFALL)] <- 0`

That makes the asumption that RAINYDAYS is correctly zero and RAINFALL is erroneously nonzero for these months.

**Comment by goldingn** [comment]
reprex on new coords for completeness:
``` r
library(NicheMapR)
micro <- micro_global(
  loc = c(73.0,  22.9),
  timeinterval = 365,
  rainfrac = 0
)
#> If program is crashing, try run.gads = 2.
#> extracting climate data
#> extracting soil moisture data
#> running microclimate model for 365 days by 1 years at site long 73 lat 22.9
#> Note: the output column `SOLR` in metout and shadmet is for unshaded horizontal plane solar radiation
#> Error in microclimate(micro): NA/NaN/Inf in foreign function call (arg 24)
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mrke** [comment]
Great and thanks for the new lingo – ‘reprex’!
