### ISSUE TITLE
question than issue

### ISSUE THREAD

**Issue by fipoucat** [mrke/NicheMapR#25]
Hello Marc and Expert,

I am asking a question on a situation (extreme event) with rain and a drop in temperature for 4 consecutive days. This had dramatic consequences with more than 500, 000 deaths in livestock (mainly ovine). Many suspect the temperature. and I wonder if, with NichemapR, there is a way to compute a parameter linked to temperature that can explain this or any suggestion? I am a climatolodist not an ecologist.

Thank you

**Comment by mrke** [comment]
You could certainly calculate that with the endotherm model of NicheMapR described in the attached. You’d need to learn quite a bit about the theory to properly apply it properly though.

From: fipoucat ***@***.***>
Sent: Wednesday, October 11, 2023 10:03 PM
To: mrke/NicheMapR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mrke/NicheMapR] question than issue (Issue #25)


Hello Marc and Expert,

I am asking a question on a situation (extreme event) with rain and a drop in temperature for 4 consecutive days. This had dramatic consequences with more than 500, 000 deaths in livestock (mainly ovine). Many suspect the temperature. and I wonder if, with NichemapR, there is a way to compute a parameter linked to temperature that can explain this or any suggestion? I am a climatolodist not an ecologist.

Thank you

**Comment by fipoucat** [comment]
Did you attach the file?

**Comment by mrke** [comment]
I did but probably doesn’t work via github – better to ask questions like this directly to my email ***@***.******@***.***> or via the google group for NicheMapR. The link to the paper is here: https://onlinelibrary.wiley.com/doi/epdf/10.1111/ecog.05550
