### ISSUE TITLE
elf_dynamic_array_reader.h:61 tag not found

### ISSUE THREAD

**Issue by bonushenricus** [mrke/NicheMapR#26]
I tried https://mrke.github.io/NicheMapR/inst/doc/microclimate-hourly-input-example
but at the end the command
micro <- microclimate(microin)
done some trouble in fortran:
elf_dynamic_array_reader.h:61 tag not found
I have Linux Debian 12, with fortran 12

**Comment by mrke** [comment]
From googling your error it seems that you are using the binary to install and that binary is not compatible with your system. Did you try installing it by compiling it? I.e. devtools::install_github('mrke/NicheMapR')

**Comment by bonushenricus** [comment]
When I install with devtools this waring appears: Warning: Fortran 2018 deleted feature: Arithmetic IF statement at (1)
The problem isn't resolve.

**Comment by mrke** [comment]
There are often warnings about old fortran features from different compilers. But did the compilation finish and could you load the package? What you reported isn't an error and so I can't suggest anything.
