### ISSUE TITLE
Issue about the combination of DEB and Endotherm

### ISSUE THREAD

**Issue by yjtw** [mrke/NicheMapR#28]
Hello, I have installed the NicheMapR. I noticed that the DEB model only has examples of combining with Ectotherm model, but there are no examples of combining with Endotherm model. I hope to try simulating the feeding and physiological characteristics of sheep and other livestock under different climate conditions. Could this be achieved through the combination of DEB and Endotherm model? If possible, what should I do? Thank you, looking forward to your reply.

**Comment by mrke** [comment]
No you would need to run the endotherm model then run the DEB model iteratively. I've been developing how to do this and integrate the heat budget and should put an example out this year.

**Comment by yjtw** [comment]
Thanks for your reply! I am looking forward to the example.
