### ISSUE TITLE
Inconsistent air temperature from the outputs of micro_global() and ectotherm()

### ISSUE THREAD

**Issue by Haowen-He** [mrke/NicheMapR#29]
When I was running through the ecotherm vignette, I found that air temperature TALOC in shadmet from micro_global() is very different from air temperature TA in environ from ectotherm(), for the same location. Any insights and/or interpretations would be appreciated. Thanks.

```
# example code
longlat <- c(139.3109, -33.888) 
loc <- longlat
ystart <- 2008
yfinish <- 2010
nyears <- yfinish - ystart + 1
micro <- micro_global(loc = longlat, nyears = nyears)
ecto <- ectotherm(nyears = nyears)

# output
min(as.data.frame(ect$environ)$TA) =7.219361
min(as.data.frame(micro$shadmet)$TALOC) = 5.195637
```

**Comment by mrke** [comment]
The output in the ectotherm model is what the simulated animal experienced as a result of its behaviour (e.g., moving between sun and shade conditions, moving below ground, climbing).
