### ISSUE TITLE
Looks for libR.dylib in the wrong place

### ISSUE THREAD

**Issue by mpinsky** [mrke/NicheMapR#4]
After installing NicheMapR 1.1.3 on a Mac OS X using R 3.4.2, the library failed to load with the following error. Notice that it is looking in the R version 3.3 folder for libR.dylib:

Loading required package: NicheMapR
Error: package or namespace load failed for ‘NicheMapR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/NicheMapR/libs/gads.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/NicheMapR/libs/gads.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/NicheMapR/libs/gads.so
  Reason: image not found

I manually created the path for /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/ and copied in libR.dylib from the 3.4 path. NicheMapR then loaded successfully.

**Comment by simon-tarr** [comment]
Hi @mpinsky I'm getting the same error with the latest version. Excuse my ignorance but could you explain how you manually created the path for  /Library/Frameworks/R.framework/Versions/3.3/Resources/lib/ and copied in libR.dylib?

**Comment by mpinsky** [comment]
I created those folders manually from within my operating system and then
copied libR.dylib from it's location associated with a different version of
R (3.4 as I remember). Not an elegant solution, but it seems to have worked.

**Comment by mrke** [comment]
Hi Malin,

Sorry, I haven't had a chance to look into this yet. I'll try and sort it out in the next week.

All the best,
Mike

**Comment by mrke** [comment]
Hi Malin and Simon,

I think this issue might be independent of the NicheMapR package per se and instead to do with your installation of R. In the microrun script there's code to find the path to your executables, pasted below, but I can't see that this would be related to the issue of finding the libR.dylib library.

 os = Sys.info()['sysname']
  if (os == "Windows") {
      if (R.Version()$arch=="x86_64") {
        libpath='/NicheMapR/libs/win/x64/microclimate.dll'
      } else {
        libpath='/NicheMapR/libs/win/i386/microclimate.dll'
      }
  } else if (os == "Linux") {
      libpath='/NicheMapR/libs/linux/MICROCLIMATE.so'
  } else if (os == "Darwin") {
      libpath='/NicheMapR/libs/mac/MICROCLIMATE.so'
}

All the best,
Mike
