### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by megbalk** [mrke/NicheMapR#6]
Which version of R does this run on?

**Comment by megbalk** [comment]
I ask because after re-installing NicheMapR I get this error: 
Error: package or namespace load failed for ‘NicheMapR’:
 package ‘NicheMapR’ was installed before R 4.0.0: please re-install it

I recently updated to R 4.0.0

**Comment by mrke** [comment]
Hi Megan,

How are you installing it?

All the best,
Mike

**Comment by megbalk** [comment]
@mrke using this code:
install.packages("NicheMapR_2.0.0.tgz", repos = NULL, type = .Platform$pkgType)

**Comment by mrke** [comment]
Can you try:

devtools::install_github('mrke/NicheMapR')

**Comment by megbalk** [comment]
I get a new error! It says that I don't have the necessary tools now and it takes me to this page: https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/

It is unclear what I need to download from this page.

**Comment by megbalk** [comment]
Now that it's installed, I am getting a new issue, which I think is still related to the version of R:

Error in dyn.load(paste0(lib.loc = .libPaths()[1], libpath)) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR/libs/mac/SOLVENDO.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR/libs/mac/SOLVENDO.so, 6): Library not loaded: /Library/Frameworks/R.framework/**Versions/3.5**/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR/libs/mac/SOLVENDO.so
  Reason: image not found

I bolded the versioning issue.

**Comment by mrke** [comment]
Hi Megan,

I haven’t seen that before and it might be to do with how things are set up at your end. But this might help:

https://community.rstudio.com/t/every-libraries-failed-to-load-after-upgrading-r-to-3-6-0/29736/22

All the best,
Mike

**Comment by megbalk** [comment]
I'll try to download an older version of R (3.5) and see if that works. Have you tested it using R v 4.0.0?

**Comment by fipoucat** [comment]
getting error while installing on R 4.0 using : devtools::install_github('mrke/NicheMapR')

**Comment by mrke** [comment]
what is the error? what OS are you installing to?

**Comment by fipoucat** [comment]
I am using Osx: 
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
Error: Failed to install 'NicheMapR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//Rtmpn21s9C/file219e62a98747/NicheMapR_3.0.0.tar.gz’ had non-zero exit status

**Comment by mrke** [comment]
try:
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true") 

then try installing again and let me know if that solves it

**Comment by fipoucat** [comment]
Maybe more output on the error which is still here:

*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘NicheMapR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-NicheMapR/00new/NicheMapR/libs/NicheMapR.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-NicheMapR/00new/NicheMapR/libs/NicheMapR.so, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/libquadmath.0.dylib
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//Rtmpn21s9C/file219e7dcc88de/NicheMapR_3.0.0.tar.gz’ had non-zero exit status

**Comment by mrke** [comment]
Perhaps try installing the latest gfortran for your version of OSX

**Comment by fipoucat** [comment]
I"ll explore this to see if it works.

**Comment by fipoucat** [comment]
Still install error, wonder if a binary with R version is available? 
Is it possible to use ERA5 with this package, working on a West Africa country?
Thanks

**Comment by mrke** [comment]
Are you seeing it compile the Fortran code during the install?

Releases are here, including binaries: https://github.com/mrke/NicheMapR/releases

more info is at https://mrke.github.io/

and the new function (not in the latest release) micro_era5 will use the ERA5 data (but so too with the micro_ncep function - see Kearney, M.R., Gillingham, P.K., Bramer, I., Duffy, J.P. & Maclean, I.M.D. (2020). A method for computing hourly, historical, terrain-corrected microclimate anywhere on earth. Methods in Ecology and Evolution 11, 38–43.)

**Comment by fipoucat** [comment]
I tried to understand the error because for some reason it still can't compile even with a gfortran upgrade?

For the binary it says compile with R version 3:
>library(NicheMapR)
Error: package or namespace load failed for ‘NicheMapR’:
 package ‘NicheMapR’ was installed before R 4.0.0: please re-install it

**Comment by mrke** [comment]
Can you tell me in as much detail as possible what you are doing and what the outcome is? I.e. please include all the steps, commands and messages/warnings.

**Comment by fipoucat** [comment]
For the source I use the below command:
devtools::install_github("mrke/nichemapr")

which end up with warnings and error messages:
arning: 'e' may be used uninitialized in this function [-Wmaybe-uninitialized]
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c gads.f -o gads.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o NicheMapR.so AACOMMONDAT.o ABOVEGROUND.o ADJREC.o BELOWGROUND.o BLKDATA.o BREED.o BTRFLGEOM.o BURROWIN.o COMMONDAT.o COND.o CONV.o CONV_ENDO.o DCHXY.o DEB.o DEB_BABY.o DEB_EULER.o DEB_HOLO.o DEVRESET.o DEXPI.o DGET_AELES.o DGET_AVELHS.o DGET_DEB.o DGET_EEES.o DGET_ELH.o DOPRI5.o DRYAIR.o DSUB.o ECTOTHERM.o ERRMSG.o EVALXZ.o EVAP.o FUN.o FUNC.o FUNSKIN.o FUNWING.o GAMMA.o GEOM.o GEOM_ENDO.o GETKFUR.o INFIL.o IOSOLR.o IRPROP.o ISPLINE.o MET.o MICRO.o MICROCLIMATE.o MICROSEGMT.o ONELUMP.o OSUB.o PARECT.o PHOTOPERIOD.o POLINT.o QROMB.o RADIN.o RADOUT.o RELHUMID.o RESP.o RESPFUN.o RYTREC.o SEAWATER.o SELDEP.o SEVAP.o SEVAP_ENDO.o SFODE.o SHADEADJUST.o SIMULSOL.o SINEC.o SNOWLAYER.o SOILPROPS.o SOLAR.o SOLAR_ENDO.o SOLOUT.o SOLRAD.o SOLVENDO.o SPLINE.o TAB.o THERMO.o TIMCON.o TRAPHR.o TRAPZD.o VAPPRS.o VSINE.o WATER.o WETAIR.o WINGS.o WING_SOLAR.o ZBRAC.o ZBRENT.o ZBRENT_ENDO.o gads.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: could not create compact unwind for _deb_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _ectotherm_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _osub_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _solvendo_: stack subq instruction is too different from dwarf stack size
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-NicheMapR/00new/NicheMapR/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘NicheMapR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-NicheMapR/00new/NicheMapR/libs/NicheMapR.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-NicheMapR/00new/NicheMapR/libs/NicheMapR.so, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/libquadmath.0.dylib
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
Error: Failed to install 'NicheMapR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/wb/pry3ghxn4s30_yrgyynbrxs80000gn/T//Rtmp8AY9Zh/file44d691975c7/NicheMapR_3.0.0.tar.gz’ had non-zero exit status

**Comment by mrke** [comment]
I think this is a local configuration issue at your end. The warnings are not a problem - I see the same ones when I install on a mac. I just tried again to install via github on my mac (running R version 4 and Catalina) and it worked fine. I can only suggest you try reinstalling R, or perhaps try installing to a different location. Might be worth trying to install another package from that uses Fortran and one that doesn't to see if it is a specific compiler issue.

**Comment by fipoucat** [comment]
Thank you, I agree too certainly something local. I'll leave it for now waiting the next R version release to see if install works?

**Comment by fipoucat** [comment]
Sorry Micheal, does this mean that to have micro_era5 you have to install an older version or wait the next one?

Thank you

**Comment by mrke** [comment]
You can just download the function from github and source it locally - it should work fine.

**Comment by fipoucat** [comment]
I am getting an error;

Error: package 'mcera5' is needed. Please install it.

Is-it another R package or?
Can you package be used with locale climate zone from WUDAPT?

Thank you

**Comment by mrke** [comment]
yes it's another package you need to install, see ?micro_era5 - please post any further questions at https://groups.google.com/forum/#!forum/nichemapr where there has already been some discussion on micro_era5

**Comment by fipoucat** [comment]
I tried many attempts to join the group without success, wonder why?

**Comment by fipoucat** [comment]
Ok, fine now.

Thank you so much
