### ISSUE TITLE
Latest commit breaks compilation

### ISSUE THREAD

**Issue by spco** [mrke/NicheMapR#7]
Hi, the latest commit 141b3c2 has broken compilation for me under R3.6.3:

```
> library(devtools) # Required to install packages from Github
> devtools::install_github("mrke/nichemapr")

....


** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘NicheMapR’ in namespaceExport(ns, exports):
 undefined exports: micro_aust_forecast
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/NicheMapR’
Error: Failed to install 'NicheMapR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/pj/5gycy5z54mb8x318q07v8kx80000gn/T//Rtmp2MJqpM/file122b67528a72d/NicheMapR_2.0.0.tar.gz’ had non-zero exit status
Execution halted
```
Compilation was successful yesterday before this change.

Thanks!

**Comment by spco** [comment]
For now I can of course just 
`devtools::install_github@c52b78095dc680f2e5743b7fe953127bf5c56b83`

**Comment by mrke** [comment]
Whoops sorry Sam, forgot to update the documentation. Fixed now.

**Comment by spco** [comment]
Thank you!

**Comment by ZZZhong-Wen** [comment]
Hi Mike,
I meet the same problem, I installed the package "NicheMapR" in R 4.0.3 GUI 1.73 Catalina build (7892) of the  macOS Big Sur, 

remotes::install_github("mrke/NicheMapR")

devtools::install_github('mrke/NicheMapR')

but always
 Downloading GitHub repo mrke/NicheMapR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/mrke/NicheMapR/tarball/HEAD' failed

and I try to install.packages("/Users/jiangzhongwen/Downloads/NicheMapR_3.0.0.tgz", repos = NULL,type = .Platform$pkgType)

but it didn't show anything.

**Comment by mrke** [comment]
Hi ZZZhong-Wen - what you describe is not the same problem and may be a local issue on your computer (e.g. a firewall blockage). I recommend you try installing another package the same way and see if that too fails.

**Comment by ZZZhong-Wen** [comment]
> Hi ZZZhong-Wen - what you describe is not the same problem and may be a local issue on your computer (e.g. a firewall blockage). I recommend you try installing another package the same way and see if that too fails.

Thanks for your responses, I can install another package, for example, the remotes::install_github("everydayduffy/mcera5")

 and  I re-install R 4.0.3 and tried again, 

my code: 
devtools::install_github('mrke/NicheMapR')

but always show this

Downloading GitHub repo mrke/NicheMapR@HEAD
✓  checking for file ‘/private/var/folders/j6/0x84zvb54p3d47fzvssjs2ph0000gn/T/RtmpgEded0/remotes6631c15d4a2/mrke-NicheMapR-69109f5/DESCRIPTION’ ...
─  preparing ‘NicheMapR’:
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘NicheMapR_3.0.0.tar.gz’
   
* installing *source* package ‘NicheMapR’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c AACOMMONDAT.f -o AACOMMONDAT.o
make: gfortran: Bad CPU type in executable
make: *** [AACOMMONDAT.o] Error 1
ERROR: compilation failed for package ‘NicheMapR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/NicheMapR’
Error: Failed to install 'NicheMapR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/j6/0x84zvb54p3d47fzvssjs2ph0000gn/T//RtmpgEded0/file6634e64c1ee/NicheMapR_3.0.0.tar.gz’ had non-zero exit status

**Comment by mrke** [comment]
OK that's more info than your previous comment. It still sounds like an issue at your end and I suggest you try installing another package via install_github that requires Fortran compilation to see if it is generally a problem with your setup rather than something inherent in the package and, if so, do some internet searching on the errors and their possible solution.

**Comment by ZZZhong-Wen** [comment]
@mrke Thanks very much for your recommendations and contributions for NicheMapR, 
I solved it, the R4.0.3 matched gfortran 8.2, though the gfortran 10.2 is for  macOS 10.16 BigSur
I can't wait to try the functions of NicheMapR3.0.0, 
Thanks again!

**Comment by tan-qiao-guo** [comment]
@mrke 
Hi Michael, I have problems to install NicheMapR, maybe due to gfortran versions similar to that of @ZZZhong-Wen , although I cannot figure out how to solve it by myself.
I am using a MacBook Pro (chip: Apple M1 Pro), Mac OS Monterey version 12.0.1
R version 4.1.2 
RStudio 2021.09.1 Build 372

I tried :
remotes::install_github("mrke/NicheMapR")
and get the error message:
Downloading GitHub repo mrke/NicheMapR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/mrke/NicheMapR/tarball/HEAD' failed

I tried:
install.packages("NicheMapR_3.1.0.tgz", repos = NULL, 
                 type = .Platform$pkgType)

There seems no response, when I type:
library(NicheMapR)

I get the error message:

Error: package or namespace load failed for ‘NicheMapR’:
 package ‘NicheMapR’ was installed before R 4.0.0: please re-install it
> 
Would you please advise how to install NicheMapR in my case? Many thanks!

**Comment by tan-qiao-guo** [comment]
> @mrke Hi Michael, I have problems to install NicheMapR, maybe due to gfortran versions similar to that of @ZZZhong-Wen , although I cannot figure out how to solve it by myself. I am using a MacBook Pro (chip: Apple M1 Pro), Mac OS Monterey version 12.0.1 R version 4.1.2 RStudio 2021.09.1 Build 372
> 
> I have installed gfortran-Intel-11.2-Monterey.dmg
> 
> I tried : remotes::install_github("mrke/NicheMapR") and get the error message: Downloading GitHub repo mrke/NicheMapR@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet, : download from 'https://api.github.com/repos/mrke/NicheMapR/tarball/HEAD' failed
> 
> I tried: install.packages("NicheMapR_3.1.0.tgz", repos = NULL, type = .Platform$pkgType)
> 
> There seems no response, when I type: library(NicheMapR)
> 
> I get the error message:
> 
> Error: package or namespace load failed for ‘NicheMapR’: package ‘NicheMapR’ was installed before R 4.0.0: please re-install it
> 
> > 
> 
> Would you please advise how to install NicheMapR in my case? Many thanks!

I have solved the installing problems by myself, below are what I did:
1. Dowload the package file from this link: https://api.github.com/repos/mrke/NicheMapR/tarball/HEAD
2. Install several dependency packages:  install.packages(c('ncdf4', 'RNetCDF', 'raster', 'deSolve' ))
3. In R (not RStudio), install using the file downloaded at step 1 using "Package Installer/ Local Source Package"
